spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
#MySQL
  write:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/disease2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        initializeSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testonReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

#MySQL
  read:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/disease2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initializeSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testonReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20